<?php
    return [
        'menu' => [
            [
                'label' => 'Dashboard',
                'route' => 'web.index',
                'icon'  => 'bi-house-fill',
            ],
            [
                'label' => 'Master',
                'icon'  => 'bi-gear',
                'children' => [
                    ['label' => 'Karyawan', 'route' => 'web.employee.index'],
                    ['label' => 'Kendaraan', 'route' => 'web.vehicle.index'],
                    ['label' => 'Asuransi', 'route' => 'web.insurance.index'],
                    ['label' => 'Perusahaan', 'route' => 'web.company.index'],
                    ['label' => 'Jabatan', 'route' => 'web.position.index'],
                    ['label' => 'Departemen', 'route' => 'web.department.index'],
                    ['label' => 'Cabang', 'route' => 'web.branch.index'],
                ]
            ]
        ],
        "sex" => [
            ["id" => "1", "name" => "Pria"],
            ["id" => "2", "name" => "Wanita"],
        ],
        "education" => [
            ["id" => "1", "name" => "TK"],
            ["id" => "2", "name" => "SD"],
            ["id" => "3", "name" => "SMP"],
            ["id" => "4", "name" => "SMA"],
            ["id" => "5", "name" => "SMU"],
            ["id" => "6", "name" => "SMK"],
            ["id" => "7", "name" => "SLTA"],
            ["id" => "8", "name" => "SLTP"],
            ["id" => "9", "name" => "D3"],
            ["id" => "10", "name" => "D4"],
            ["id" => "11", "name" => "S1"],
            ["id" => "12", "name" => "S2"],
            ["id" => "13", "name" => "S3"],
        ],
        "religions" => [
            ["id" => "1", "name" => "Islam"],
            ["id" => "2", "name" => "Kristen"],
            ["id" => "3", "name" => "Katholik"],
            ["id" => "4", "name" => "Buddha"],
            ["id" => "5", "name" => "Hindu"],
            ["id" => "6", "name" => "Kong Hu Cu"],
        ],
        "blood_type" => [
            ["id" => "1", "name" => "A"],
            ["id" => "2", "name" => "A+"],
            ["id" => "3", "name" => "A-"],
            ["id" => "4", "name" => "B"],
            ["id" => "5", "name" => "B+"],
            ["id" => "6", "name" => "B-"],
            ["id" => "7", "name" => "AB"],
            ["id" => "8", "name" => "AB+"],
            ["id" => "9", "name" => "AB-"],
            ["id" => "10", "name" => "O"],
            ["id" => "11", "name" => "O+"],
            ["id" => "12", "name" => "O-"],
        ],
        "marriage" => [
            ["id" => "1", "name" => "TK-0"],
            ["id" => "2", "name" => "TK-1"],
            ["id" => "3", "name" => "TK-2"],
            ["id" => "4", "name" => "TK-3"],
            ["id" => "5", "name" => "TK-4"],
            ["id" => "6", "name" => "TK-5"],
            ["id" => "7", "name" => "K-0"],
            ["id" => "8", "name" => "K-1"],
            ["id" => "9", "name" => "K-2"],
            ["id" => "10", "name" => "K-3"],
            ["id" => "11", "name" => "K-4"],
            ["id" => "12", "name" => "K-5"],
        ],
        "colors" => [
            [ "id" => 1, "name"=> "White", "code"=> "#FFFFFF" ],
            [ "id" => 2, "name"=> "Black", "code"=> "#000000" ],
            [ "id" => 3, "name"=> "Silver", "code"=> "#C0C0C0" ],
            [ "id" => 4, "name"=> "Gray", "code"=> "#808080" ],
            [ "id" => 5, "name"=> "Red", "code"=> "#FF0000" ],
            [ "id" => 6, "name"=> "Blue", "code"=> "#0000FF" ],
            [ "id" => 7, "name"=> "Brown", "code"=> "#8B4513" ],
            [ "id" => 8, "name"=> "Green", "code"=> "#008000" ],
            [ "id" => 9, "name"=> "Yellow", "code"=> "#FFFF00" ],
            [ "id" => 10, "name"=> "Orange", "code"=> "#FFA500" ],
            [ "id" => 11, "name"=> "Gold", "code"=> "#FFD700" ],
            [ "id" => 12, "name"=> "Beige", "code"=> "#F5F5DC" ],

            [ "id" => 13, "name"=> "Pearl White", "code"=> "#F8F8FF" ],
            [ "id" => 14, "name"=> "Metallic Silver", "code"=> "#B0B0B0" ],
            [ "id" => 15, "name"=> "Gunmetal Gray", "code"=> "#2A3439" ],
            [ "id" => 16, "name"=> "Charcoal Gray", "code"=> "#36454F" ],
            [ "id" => 17, "name"=> "Midnight Black", "code"=> "#0D0D0D" ],

            [ "id" => 18, "name"=> "Candy Red", "code"=> "#D2042D" ],
            [ "id" => 19, "name"=> "Burgundy", "code"=> "#800020" ],
            [ "id" => 20, "name"=> "Maroon", "code"=> "#800000" ],

            [ "id" => 21, "name"=> "Navy Blue", "code"=> "#000080" ],
            [ "id" => 22, "name"=> "Sky Blue", "code"=> "#87CEEB" ],
            [ "id" => 23, "name"=> "Electric Blue", "code"=> "#007FFF" ],

            [ "id" => 24, "name"=> "Racing Green", "code"=> "#004225" ],
            [ "id" => 25, "name"=> "Olive Green", "code"=> "#808000" ],
            [ "id" => 26, "name"=> "Lime Green", "code"=> "#32CD32" ],

            [ "id" => 27, "name"=> "Sunset Orange", "code"=> "#FF4500" ],
            [ "id" => 28, "name"=> "Burnt Orange", "code"=> "#CC5500" ],

            [ "id" => 29, "name"=> "Champagne", "code"=> "#F7E7CE" ],
            [ "id" => 30, "name"=> "Bronze", "code"=> "#CD7F32" ],
            [ "id" => 31, "name"=> "Copper", "code"=> "#B87333" ],

            [ "id" => 32, "name"=> "Matte Black", "code"=> "#1C1C1C" ],
            [ "id" => 33, "name"=> "Matte Gray", "code"=> "#6E6E6E" ],
            [ "id" => 34, "name"=> "Matte White", "code"=> "#EDEDED" ],

            [ "id" => 35, "name"=> "Pearl Blue", "code"=> "#4D6FA9" ],
            [ "id" => 36, "name"=> "Pearl Red", "code"=> "#B22222" ],
            [ "id" => 37, "name"=> "Pearl Green", "code"=> "#2E8B57" ]
        ],
        'brands' => [
            [ "id" => 1, "type"=> "car", "name"=> "Toyota" ],
            [ "id" => 2, "type"=> "car", "name"=> "Honda" ],
            [ "id" => 3, "type"=> "car", "name"=> "Nissan" ],
            [ "id" => 4, "type"=> "car", "name"=> "Mazda" ],
            [ "id" => 5, "type"=> "car", "name"=> "Subaru" ],
            [ "id" => 6, "type"=> "car", "name"=> "Mitsubishi" ],
            [ "id" => 7, "type"=> "car", "name"=> "Suzuki" ],
            [ "id" => 8, "type"=> "car", "name"=> "Daihatsu" ],
            [ "id" => 9, "type"=> "car", "name"=> "Lexus" ],
            [ "id" => 10, "type"=> "car", "name"=> "Infiniti" ],
            [ "id" => 11, "type"=> "car", "name"=> "Acura" ],

            [ "id" => 12, "type"=> "car", "name"=> "Hyundai" ],
            [ "id" => 13, "type"=> "car", "name"=> "Kia" ],
            [ "id" => 14, "type"=> "car", "name"=> "Genesis" ],

            [ "id" => 15, "type"=> "car", "name"=> "Ford" ],
            [ "id" => 16, "type"=> "car", "name"=> "Chevrolet" ],
            [ "id" => 17, "type"=> "car", "name"=> "GMC" ],
            [ "id" => 18, "type"=> "car", "name"=> "Cadillac" ],
            [ "id" => 19, "type"=> "car", "name"=> "Chrysler" ],
            [ "id" => 20, "type"=> "car", "name"=> "Dodge" ],
            [ "id" => 21, "type"=> "car", "name"=> "Jeep" ],
            [ "id" => 22, "type"=> "car", "name"=> "Tesla" ],

            [ "id" => 23, "type"=> "car", "name"=> "BMW" ],
            [ "id" => 24, "type"=> "car", "name"=> "Mercedes-Benz" ],
            [ "id" => 25, "type"=> "car", "name"=> "Audi" ],
            [ "id" => 26, "type"=> "car", "name"=> "Volkswagen" ],
            [ "id" => 27, "type"=> "car", "name"=> "Porsche" ],
            [ "id" => 28, "type"=> "car", "name"=> "Volvo" ],
            [ "id" => 29, "type"=> "car", "name"=> "Jaguar" ],
            [ "id" => 30, "type"=> "car", "name"=> "Land Rover" ],
            [ "id" => 31, "type"=> "car", "name"=> "Mini" ],
            [ "id" => 32, "type"=> "car", "name"=> "Bentley" ],
            [ "id" => 33, "type"=> "car", "name"=> "Rolls-Royce" ],

            [ "id" => 34, "type"=> "car", "name"=> "Ferrari" ],
            [ "id" => 35, "type"=> "car", "name"=> "Lamborghini" ],
            [ "id" => 36, "type"=> "car", "name"=> "Maserati" ],
            [ "id" => 37, "type"=> "car", "name"=> "Alfa Romeo" ],

            [ "id" => 38, "type"=> "car", "name"=> "Peugeot" ],
            [ "id" => 39, "type"=> "car", "name"=> "Renault" ],
            [ "id" => 40, "type"=> "car", "name"=> "Citroen" ],
            [ "id" => 41, "type"=> "car", "name"=> "Skoda" ],
            [ "id" => 42, "type"=> "car", "name"=> "SEAT" ],

            [ "id" => 43, "type"=> "car", "name"=> "Geely" ],
            [ "id" => 44, "type"=> "car", "name"=> "Chery" ],
            [ "id" => 45, "type"=> "car", "name"=> "BYD" ],
            [ "id" => 46, "type"=> "car", "name"=> "Great Wall" ],
            [ "id" => 47, "type"=> "car", "name"=> "Wuling" ],

            [ "id" => 48, "type"=> "truck", "name"=> "Isuzu" ],
            [ "id" => 49, "type"=> "truck", "name"=> "Hino" ],
            [ "id" => 50, "type"=> "truck", "name"=> "Fuso" ],

            [ "id" => 51, "type"=> "truck", "name"=> "Ford Trucks" ],
            [ "id" => 52, "type"=> "truck", "name"=> "Chevrolet Trucks" ],
            [ "id" => 53, "type"=> "truck", "name"=> "GMC Trucks" ],
            [ "id" => 54, "type"=> "truck", "name"=> "Ram" ],

            [ "id" => 55, "type"=> "truck", "name"=> "Mercedes-Benz Trucks" ],
            [ "id" => 56, "type"=> "truck", "name"=> "MAN" ],
            [ "id" => 57, "type"=> "truck", "name"=> "Scania" ],
            [ "id" => 58, "type"=> "truck", "name"=> "Volvo Trucks" ],
            [ "id" => 59, "type"=> "truck", "name"=> "DAF" ],
            [ "id" => 60, "type"=> "truck", "name"=> "Iveco" ],

            [ "id" => 61, "type"=> "truck", "name"=> "Kenworth" ],
            [ "id" => 62, "type"=> "truck", "name"=> "Peterbilt" ],
            [ "id" => 63, "type"=> "truck", "name"=> "Freightliner" ],
            [ "id" => 64, "type"=> "truck", "name"=> "Mack" ],

            [ "id" => 65, "type"=> "truck", "name"=> "Tata Motors" ],
            [ "id" => 66, "type"=> "truck", "name"=> "Ashok Leyland" ],

            [ "id" => 67, "type"=> "truck", "name"=> "Dongfeng" ],
            [ "id" => 68, "type"=> "truck", "name"=> "FAW" ],
            [ "id" => 69, "type"=> "truck", "name"=> "Sinotruk" ],
            [ "id" => 70, "type"=> "truck", "name"=> "Foton" ],

            [ "id" => 71, "type"=> "heavy", "name"=> "Caterpillar" ],
            [ "id" => 72, "type"=> "heavy", "name"=> "Komatsu" ],
            [ "id" => 73, "type"=> "heavy", "name"=> "Hitachi Construction Machinery" ],
            [ "id" => 74, "type"=> "heavy", "name"=> "Volvo Construction Equipment" ],
            [ "id" => 75, "type"=> "heavy", "name"=> "Liebherr" ],
            [ "id" => 76, "type"=> "heavy", "name"=> "Doosan" ],
            [ "id" => 77, "type"=> "heavy", "name"=> "Hyundai Construction Equipment" ],

            [ "id" => 78, "type"=> "heavy", "name"=> "JCB" ],
            [ "id" => 79, "type"=> "heavy", "name"=> "CASE Construction" ],
            [ "id" => 80, "type"=> "heavy", "name"=> "New Holland Construction" ],
            [ "id" => 81, "type"=> "heavy", "name"=> "Bobcat" ],

            [ "id" => 82, "type"=> "heavy", "name"=> "Sany" ],
            [ "id" => 83, "type"=> "heavy", "name"=> "XCMG" ],
            [ "id" => 84, "type"=> "heavy", "name"=> "Zoomlion" ],
            [ "id" => 85, "type"=> "heavy", "name"=> "LiuGong" ],

            [ "id" => 86, "type"=> "heavy", "name"=> "Kubota" ],
            [ "id" => 87, "type"=> "heavy", "name"=> "Takeuchi" ],

            [ "id" => 88, "type"=> "heavy", "name"=> "Terex" ],
            [ "id" => 89, "type"=> "heavy", "name"=> "Wirtgen Group" ]
        ]
    ];
?>
